### ISSUE TITLE
[feat] 사용자 맞춤형 페이지

### ISSUE THREAD

**Issue by eunnnju** [MetalRoze/OnlineNews_FE#32]
## 📍이슈 요약  
사용자 맞춤형 페이지 제작

## ✅ Todo 
- [x] 구독하고 있는 신문사 보여주는 컴포넌트
- [x]  신문사 종류 슬라이드 바
- [x] 신문사 프로필 컴포넌트 (재사용)
